-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 12:33:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbpersonal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpersonal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbpersonal` DEFAULT CHARACTER SET utf8 ;
USE `dbpersonal` ;

-- -----------------------------------------------------
-- Table `dbpersonal`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `dni` INT(8) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(15) NOT NULL,
  `telefono` INT NULL,
  `nacimiento` DATE NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idempleado`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `idempleado_UNIQUE` (`idempleado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_puesto` VARCHAR(45) NOT NULL,
  `sueldo` DECIMAL NOT NULL,
  PRIMARY KEY (`idcargo`),
  UNIQUE INDEX `idpuestos_UNIQUE` (`idcargo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`area` (
  `idarea` INT NOT NULL,
  `nombre_area` VARCHAR(45) NOT NULL,
  `idcargo` INT NOT NULL,
  PRIMARY KEY (`idarea`),
  UNIQUE INDEX `idarea_UNIQUE` (`idarea` ASC) ,
  INDEX `fk_area_cargo_idx` (`idcargo` ASC) ,
  CONSTRAINT `fk_area_cargo`
    FOREIGN KEY (`idcargo`)
    REFERENCES `dbpersonal`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`cuestionario` (
  `idcuestionario` INT NOT NULL AUTO_INCREMENT,
  `nombre_cuestionario` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcuestionario`),
  UNIQUE INDEX `idcuestionario_UNIQUE` (`idcuestionario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) ,
  INDEX `fk_usuario_empleado1_idx` (`empleado_idempleado` ASC) ,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `dbpersonal`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`actividades` (
  `idactividades` INT NOT NULL,
  `fecha_llenado` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `cuestionario_idcuestionario` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `fecha_mod` DATETIME NOT NULL,
  PRIMARY KEY (`idactividades`),
  INDEX `fk_actividades_cuestionario1_idx` (`cuestionario_idcuestionario` ASC) ,
  INDEX `fk_actividades_usuario1_idx` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_actividades_cuestionario1`
    FOREIGN KEY (`cuestionario_idcuestionario`)
    REFERENCES `dbpersonal`.`cuestionario` (`idcuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `dbpersonal`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`pregunta` (
  `idpregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` TEXT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idpregunta`),
  UNIQUE INDEX `idpregunta_UNIQUE` (`idpregunta` ASC) ,
  INDEX `fk_pregunta_categoria1_idx` (`categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_pregunta_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `dbpersonal`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`alternativa` (
  `idalternativa` INT NOT NULL AUTO_INCREMENT,
  `valor_alternativa` INT NOT NULL,
  PRIMARY KEY (`idalternativa`),
  UNIQUE INDEX `idalternativa_UNIQUE` (`idalternativa` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`pregunta_cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`pregunta_cuestionario` (
  `id_pregunta_cuestionaro` INT NOT NULL AUTO_INCREMENT,
  `cuestionario_idcuestionario` INT NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  `alternativa_idalternativa` INT NOT NULL,
  `pregunta_cuestionariocol` VARCHAR(45) NULL,
  INDEX `fk_pregunta_cuestionario_pregunta1_idx` (`pregunta_idpregunta` ASC) ,
  INDEX `fk_pregunta_cuestionario_cuestionario1_idx` (`cuestionario_idcuestionario` ASC) ,
  PRIMARY KEY (`id_pregunta_cuestionaro`),
  UNIQUE INDEX `id_pregunta_cuestionaro_UNIQUE` (`id_pregunta_cuestionaro` ASC),
  INDEX `fk_pregunta_cuestionario_alternativa_idx` (`alternativa_idalternativa` ASC) ,
  CONSTRAINT `fk_pregunta_cuestionario_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta`)
    REFERENCES `dbpersonal`.`pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_cuestionario_cuestionario1`
    FOREIGN KEY (`cuestionario_idcuestionario`)
    REFERENCES `dbpersonal`.`cuestionario` (`idcuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_cuestionario_alternativa`
    FOREIGN KEY (`alternativa_idalternativa`)
    REFERENCES `dbpersonal`.`alternativa` (`idalternativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`respuesta_individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`respuesta_individual` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `empleado_idempleado` INT NOT NULL,
  `pregunta_cuestionario_id_pregunta_cuestionaro` INT NOT NULL,
  `fecha_respuesta` DATETIME NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  UNIQUE INDEX `idrespuesta_UNIQUE` (`idrespuesta` ASC) ,
  INDEX `fk_respuesta_empleado1_idx` (`empleado_idempleado` ASC) ,
  INDEX `fk_respuesta_pregunta_cuestionario1_idx` (`pregunta_cuestionario_id_pregunta_cuestionaro` ASC) ,
  CONSTRAINT `fk_respuesta_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `dbpersonal`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_pregunta_cuestionario1`
    FOREIGN KEY (`pregunta_cuestionario_id_pregunta_cuestionaro`)
    REFERENCES `dbpersonal`.`pregunta_cuestionario` (`id_pregunta_cuestionaro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`resultado_encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`resultado_encuesta` (
  `idresultados` INT NOT NULL AUTO_INCREMENT,
  `empleado_idempleado` INT NOT NULL,
  `respuesta_idrespuesta` INT NOT NULL,
  `puntaje_total` INT NOT NULL,
  `certificado` TINYINT NOT NULL,
  PRIMARY KEY (`idresultados`),
  UNIQUE INDEX `idresultados_UNIQUE` (`idresultados` ASC) ,
  INDEX `fk_total_encuesta_empleado1_idx` (`empleado_idempleado` ASC) ,
  INDEX `fk_total_encuesta_respuesta1_idx` (`respuesta_idrespuesta` ASC) ,
  CONSTRAINT `fk_total_encuesta_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `dbpersonal`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_total_encuesta_respuesta1`
    FOREIGN KEY (`respuesta_idrespuesta`)
    REFERENCES `dbpersonal`.`respuesta_individual` (`idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpersonal`.`empleado_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpersonal`.`empleado_area` (
  `idempleado_area` INT NOT NULL,
  `idearea` INT NOT NULL,
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idempleado_area`),
  UNIQUE INDEX `idempleado_area_UNIQUE` (`idempleado_area` ASC) ,
  INDEX `fk_empeado_area_idx` (`idempleado` ASC) ,
  INDEX `fk_area_empleado_area_idx` (`idearea` ASC) ,
  CONSTRAINT `fk_empeado_empleado_area`
    FOREIGN KEY (`idempleado`)
    REFERENCES `dbpersonal`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_empleado_area`
    FOREIGN KEY (`idearea`)
    REFERENCES `dbpersonal`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
